import path from 'path'
import fs from 'fs'
import { dataDir } from './paths'
import { writeFileSafe } from './safe-file'

// Canonical ComfyUI model folder types from folder_paths.py. Must stay in sync with that list.
export const MODEL_FOLDER_TYPES = [
  'checkpoints',
  'classifiers',
  'clip_vision',
  'configs',
  'controlnet',
  'diffusers',
  'diffusion_models',
  'embeddings',
  'gligen',
  'hypernetworks',
  'latent_upscale_models',
  'loras',
  'model_patches',
  'audio_encoders',
  'photomaker',
  'style_models',
  'text_encoders',
  'upscale_models',
  'vae',
  'vae_approx'
] as const

const YAML_PATH: string = path.join(dataDir(), 'shared_model_paths.yaml')

// Canonical names plus legacy/alias directory names ComfyUI maps to canonical names.
export const KNOWN_MODEL_FOLDERS = new Set<string>([
  ...MODEL_FOLDER_TYPES,
  'clip', // legacy alias for text_encoders
  'unet', // legacy alias for diffusion_models
  't2i_adapter' // secondary dir for controlnet
])

// Folder names that must NEVER be registered as model search paths (system dirs, tooling
// dotfolders, `models` self-reference). `custom_nodes` is critical: ComfyUI's prestartup
// does `os.listdir` on every registered custom_nodes path and crashes if it's missing.
const NON_MODEL_FOLDERS = new Set<string>([
  'custom_nodes',
  'user',
  'input',
  'output',
  'temp',
  'models',
  '.venv',
  '.snapshots',
  '.git',
  '__pycache__'
])

export interface ModelPathsResult {
  yamlPath: string
  extraFolders: string[]
}

export interface SyncResult {
  newFolders: string[]
  config: ModelPathsResult | null
}

/** Lists subdirectory names, including symlinks that resolve to directories. */
function allFoldersIn(dir: string): string[] {
  try {
    return fs
      .readdirSync(dir, { withFileTypes: true })
      .filter((e) => {
        if (e.isDirectory()) return true
        if (e.isSymbolicLink()) {
          try {
            return fs.statSync(path.join(dir, e.name)).isDirectory()
          } catch {
            return false
          }
        }
        return false
      })
      .map((e) => e.name)
  } catch {
    return []
  }
}

/** Subdirectories not in KNOWN_MODEL_FOLDERS or NON_MODEL_FOLDERS. */
function extraFoldersIn(dir: string): string[] {
  return allFoldersIn(dir).filter(
    (name) => !KNOWN_MODEL_FOLDERS.has(name) && !NON_MODEL_FOLDERS.has(name)
  )
}

/** Extra (custom-node-created) model folders, checking both standalone and portable layouts. */
export function discoverExtraModelFolders(installPath: string): string[] {
  const candidates = [path.join(installPath, 'ComfyUI', 'models'), path.join(installPath, 'models')]
  const seen = new Set<string>()
  for (const dir of candidates) {
    for (const name of extraFoldersIn(dir)) {
      seen.add(name)
    }
  }
  return [...seen].sort()
}

/** Deduplicated, sorted extra model folder names across all shared model directories. */
function discoverExtraFoldersFromSharedDirs(modelsDirs: string[]): string[] {
  const seen = new Set<string>()
  for (const dir of modelsDirs) {
    for (const name of extraFoldersIn(dir)) {
      seen.add(name)
    }
  }
  return [...seen].sort()
}

/**
 * Legacy directory aliases that ComfyUI's own defaults register under canonical
 * folder types (`folder_paths.py`):
 *   - `clip/` is a second path on `text_encoders` (ComfyUI's `map_legacy` maps
 *     a YAML `clip:` key to `text_encoders` automatically).
 *   - `unet/` is a second path on `diffusion_models` (same legacy mapping).
 *   - `t2i_adapter/` is a second path on `controlnet` (no legacy mapping —
 *     emitted as its own key, ComfyUI's controlnet defaults already list it).
 *
 * Without these in the YAML, shared-dir users who keep encoders in
 * `<shared>/clip/` (the historical ComfyUI layout) or diffusion models in
 * `<shared>/unet/` see their files invisible to `DualCLIPLoader` / `UNETLoader`,
 * even though Storage shows the shared dir is configured. ComfyUI's defaults
 * find them when they live under `<install>/ComfyUI/models/clip|unet/` because
 * those are baked into `folder_names_and_paths`, but the extra-paths YAML only
 * registers what we explicitly list. Emitting the aliases for every shared dir
 * keeps the shared layout on equal footing with the install's own defaults. */
const LEGACY_FOLDER_ALIASES: ReadonlyArray<{ key: string; dir: string }> = [
  { key: 'clip', dir: 'clip' },
  { key: 'unet', dir: 'unet' },
  { key: 't2i_adapter', dir: 't2i_adapter' },
]

function buildYaml(modelsDirs: string[], extraFolders: string[] = []): string {
  const allFolders = [...MODEL_FOLDER_TYPES, ...extraFolders]
  const lines = [
    '# Generated by Comfy Desktop — do not edit manually.',
    '# When ComfyUI supports all_model_folders, this file will be simplified to:',
    '#   comfy.desktop:',
    "#     base_path: '...'",
    '#     is_default: true',
    '#     all_model_folders: true',
    ''
  ]
  modelsDirs.forEach((dir, i) => {
    const escaped = dir.replace(/'/g, "''")
    lines.push(`comfy.desktop_${i}:`)
    lines.push(`  base_path: '${escaped}'`)
    if (i === 0) lines.push('  is_default: true')
    for (const folder of allFolders) {
      const escapedFolder = folder.replace(/'/g, "''")
      lines.push(`  '${escapedFolder}': '${escapedFolder}/'`)
    }
    // Emit legacy aliases AFTER the canonical entries so the canonical
    // directories (e.g. `text_encoders/`) stay first in ComfyUI's search
    // order — `add_model_folder_path` appends to the existing list.
    for (const { key, dir } of LEGACY_FOLDER_ALIASES) {
      const escapedKey = key.replace(/'/g, "''")
      const escapedDir = dir.replace(/'/g, "''")
      lines.push(`  '${escapedKey}': '${escapedDir}/'`)
    }
    lines.push('')
  })
  return lines.join('\n')
}

/**
 * Ensures the shared model paths YAML is up to date, including extra subdirectories
 * already present in the shared dirs. Returns null if no directories are configured.
 */
export function ensureModelPathsConfig(
  modelsDirs: string[] | null | undefined
): ModelPathsResult | null {
  if (!modelsDirs || !Array.isArray(modelsDirs) || modelsDirs.length === 0) return null
  const resolved = modelsDirs.map((d) => path.resolve(d))
  const extraFolders = discoverExtraFoldersFromSharedDirs(resolved)
  const yaml = buildYaml(resolved, extraFolders)

  let existing: string | null = null
  try {
    existing = fs.readFileSync(YAML_PATH, 'utf-8')
  } catch {}

  if (existing !== yaml) {
    writeFileSafe(YAML_PATH, yaml)
  }

  return { yamlPath: YAML_PATH, extraFolders }
}

/** All subdirectory names from the install's models dir, checking standalone and portable layouts. */
function allInstallModelFolders(installPath: string): string[] {
  const candidates = [path.join(installPath, 'ComfyUI', 'models'), path.join(installPath, 'models')]
  const seen = new Set<string>()
  for (const dir of candidates) {
    for (const name of allFoldersIn(dir)) {
      seen.add(name)
    }
  }
  return [...seen].sort()
}

/**
 * Syncs all model folders from the install to the shared model roots and rewrites the YAML.
 * Returns newly added extra folder names and the updated config.
 */
export function syncCustomModelFolders(
  installPath: string,
  modelsDirs: string[] | null | undefined,
  previousExtras: string[] = []
): SyncResult {
  if (!modelsDirs || !Array.isArray(modelsDirs) || modelsDirs.length === 0) {
    return { newFolders: [], config: null }
  }

  // Sync ALL folders (including canonical) so users can place models in any folder type.
  const allFolders = allInstallModelFolders(installPath)
  for (const dir of modelsDirs) {
    for (const folder of allFolders) {
      const target = path.join(dir, folder)
      try {
        fs.mkdirSync(target, { recursive: true })
      } catch {}
    }
  }

  const extraFolders = discoverExtraModelFolders(installPath)
  const previousSet = new Set(previousExtras)
  const newFolders = extraFolders.filter((f) => !previousSet.has(f))

  const config = ensureModelPathsConfig(modelsDirs)

  return { newFolders, config }
}
