import path from 'path'
import fs from 'fs'
import { dataDir } from './paths'
import { writeFileSafe } from './safe-file'

// Canonical ComfyUI model folder types from folder_paths.py.
// When ComfyUI adds `all_model_folders` support in extra_model_paths.yaml,
// this list can be replaced with a single `all_model_folders: true` flag.
export const MODEL_FOLDER_TYPES = [
  "checkpoints",
  "classifiers",
  "clip_vision",
  "configs",
  "controlnet",
  "diffusers",
  "diffusion_models",
  "embeddings",
  "gligen",
  "hypernetworks",
  "latent_upscale_models",
  "loras",
  "model_patches",
  "audio_encoders",
  "photomaker",
  "style_models",
  "text_encoders",
  "upscale_models",
  "vae",
  "vae_approx",
] as const

const YAML_PATH: string = path.join(dataDir(), "shared_model_paths.yaml")

// Canonical names + legacy/alias directory names that ComfyUI creates on disk
// but maps to canonical names (e.g. unet→diffusion_models, clip→text_encoders).
const KNOWN_MODEL_FOLDERS = new Set<string>([
  ...MODEL_FOLDER_TYPES,
  'clip',           // legacy alias for text_encoders
  'unet',           // legacy alias for diffusion_models
  't2i_adapter',    // secondary dir for controlnet
])

// Folder names that must NEVER be registered as model search paths, even if
// they appear inside a shared models directory. These are either ComfyUI
// system directories (custom_nodes, user, input, output, temp), dotfolders
// owned by tooling (.venv, .snapshots, .git, __pycache__), or the `models`
// self-reference produced when a ComfyUI install root is itself configured
// as a shared models dir.
//
// `custom_nodes` is especially important: ComfyUI's prestartup does
// `os.listdir(path)` on every registered `custom_nodes` path and crashes if
// the directory is missing under any shared base_path.
const NON_MODEL_FOLDERS = new Set<string>([
  'custom_nodes',
  'user',
  'input',
  'output',
  'temp',
  'models',
  '.venv',
  '.snapshots',
  '.git',
  '__pycache__',
])

export interface ModelPathsResult {
  yamlPath: string
  extraFolders: string[]
}

export interface SyncResult {
  newFolders: string[]
  config: ModelPathsResult | null
}

/**
 * Lists all subdirectory names in a directory, including symlinks that
 * resolve to directories.
 */
function allFoldersIn(dir: string): string[] {
  try {
    return fs.readdirSync(dir, { withFileTypes: true })
      .filter((e) => {
        if (e.isDirectory()) return true
        if (e.isSymbolicLink()) {
          try { return fs.statSync(path.join(dir, e.name)).isDirectory() } catch { return false }
        }
        return false
      })
      .map((e) => e.name)
  } catch {
    return []
  }
}

/**
 * Scans a directory for subdirectories whose names are not in
 * KNOWN_MODEL_FOLDERS and not in NON_MODEL_FOLDERS (system/tooling dirs that
 * must never be treated as model search paths).
 */
function extraFoldersIn(dir: string): string[] {
  return allFoldersIn(dir).filter(
    (name) => !KNOWN_MODEL_FOLDERS.has(name) && !NON_MODEL_FOLDERS.has(name),
  )
}

/**
 * Scans the ComfyUI models directory of an installation for subdirectories
 * that aren't in KNOWN_MODEL_FOLDERS (i.e. directories created by custom nodes).
 * Checks both `{installPath}/ComfyUI/models` (standalone) and
 * `{installPath}/models` (portable/other layouts).
 */
export function discoverExtraModelFolders(installPath: string): string[] {
  const candidates = [
    path.join(installPath, 'ComfyUI', 'models'),
    path.join(installPath, 'models'),
  ]
  const seen = new Set<string>()
  for (const dir of candidates) {
    for (const name of extraFoldersIn(dir)) {
      seen.add(name)
    }
  }
  return [...seen].sort()
}

/**
 * Collects the deduplicated, sorted set of extra model folder names present
 * in any of the shared model directories.
 */
function discoverExtraFoldersFromSharedDirs(modelsDirs: string[]): string[] {
  const seen = new Set<string>()
  for (const dir of modelsDirs) {
    for (const name of extraFoldersIn(dir)) {
      seen.add(name)
    }
  }
  return [...seen].sort()
}

function buildYaml(modelsDirs: string[], extraFolders: string[] = []): string {
  const allFolders = [...MODEL_FOLDER_TYPES, ...extraFolders]
  const lines = [
    "# Generated by Comfy Desktop — do not edit manually.",
    "# When ComfyUI supports all_model_folders, this file will be simplified to:",
    "#   comfyui_desktop_2:",
    "#     base_path: '...'",
    "#     is_default: true",
    "#     all_model_folders: true",
    "",
  ]
  modelsDirs.forEach((dir, i) => {
    const escaped = dir.replace(/'/g, "''")
    lines.push(`comfyui_desktop_2_${i}:`)
    lines.push(`  base_path: '${escaped}'`)
    if (i === 0) lines.push("  is_default: true")
    for (const folder of allFolders) {
      const escapedFolder = folder.replace(/'/g, "''")
      lines.push(`  '${escapedFolder}': '${escapedFolder}/'`)
    }
    lines.push("")
  })
  return lines.join("\n")
}

/**
 * Ensures the shared model paths YAML is up to date.
 * Automatically includes any extra subdirectories already present in the
 * shared model directories (previously discovered from custom nodes).
 * Returns the YAML path and the list of extra folders included, or null
 * if no directories are configured.
 */
export function ensureModelPathsConfig(modelsDirs: string[] | null | undefined): ModelPathsResult | null {
  if (!modelsDirs || !Array.isArray(modelsDirs) || modelsDirs.length === 0) return null
  const resolved = modelsDirs.map((d) => path.resolve(d))
  const extraFolders = discoverExtraFoldersFromSharedDirs(resolved)
  const yaml = buildYaml(resolved, extraFolders)

  let existing: string | null = null
  try {
    existing = fs.readFileSync(YAML_PATH, "utf-8")
  } catch {}

  if (existing !== yaml) {
    writeFileSafe(YAML_PATH, yaml)
  }

  return { yamlPath: YAML_PATH, extraFolders }
}

/**
 * Collects all subdirectory names from the installation's models directory,
 * checking both standalone and portable layouts.
 */
function allInstallModelFolders(installPath: string): string[] {
  const candidates = [
    path.join(installPath, 'ComfyUI', 'models'),
    path.join(installPath, 'models'),
  ]
  const seen = new Set<string>()
  for (const dir of candidates) {
    for (const name of allFoldersIn(dir)) {
      seen.add(name)
    }
  }
  return [...seen].sort()
}

/**
 * Syncs all model directories from the installation to the shared model roots,
 * ensuring every folder present in the install is available in the shared dirs.
 * Rewrites the YAML to include any extra (non-canonical) folders.
 * Returns the list of newly added extra folder names and the updated config.
 */
export function syncCustomModelFolders(
  installPath: string,
  modelsDirs: string[] | null | undefined,
  previousExtras: string[] = [],
): SyncResult {
  if (!modelsDirs || !Array.isArray(modelsDirs) || modelsDirs.length === 0) {
    return { newFolders: [], config: null }
  }

  // Sync ALL model folders (including canonical ones) to shared roots so
  // users can place models in the shared directory for any folder type.
  const allFolders = allInstallModelFolders(installPath)
  for (const dir of modelsDirs) {
    for (const folder of allFolders) {
      const target = path.join(dir, folder)
      try {
        fs.mkdirSync(target, { recursive: true })
      } catch {}
    }
  }

  // Determine which extra (non-canonical) folders are new for relaunch decisions
  const extraFolders = discoverExtraModelFolders(installPath)
  const previousSet = new Set(previousExtras)
  const newFolders = extraFolders.filter((f) => !previousSet.has(f))

  // Rewrite the YAML so subsequent launches include extra folders
  const config = ensureModelPathsConfig(modelsDirs)

  return { newFolders, config }
}
