import fs from 'node:fs'
import { Readable } from 'node:stream'
import { pipeline } from 'node:stream/promises'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const scriptDir = path.dirname(fileURLToPath(import.meta.url))
const vcRedistUrl = 'https://aka.ms/vc14/vc_redist.x64.exe'

// VS_FIXEDFILEINFO starts with dwSignature = 0xFEEF04BD followed by
// dwStrucVersion = 0x00010000 (LE). Matching both eliminates any chance of a
// false positive from the 4-byte signature appearing incidentally in code or
// data sections of the ~24 MB redist binary.
const VS_FIXEDFILEINFO_SIGNATURE = Buffer.from([0xbd, 0x04, 0xef, 0xfe, 0x00, 0x00, 0x01, 0x00])

/**
 * Read the FileVersion (a.b.c.d) from a Win32 PE executable by locating the
 * VS_FIXEDFILEINFO struct embedded in its version resource. Used to discover
 * the bundled vc_redist.x64.exe version on any host platform without shelling
 * out to Windows-only tools.
 */
function readPeFileVersion(exePath) {
  const buf = fs.readFileSync(exePath)
  const sigOffset = buf.indexOf(VS_FIXEDFILEINFO_SIGNATURE)
  if (sigOffset === -1) {
    throw new Error(`VS_FIXEDFILEINFO signature not found in ${exePath}`)
  }
  // VS_FIXEDFILEINFO layout (after the 4-byte signature):
  //   DWORD dwStrucVersion       (offset +4)
  //   DWORD dwFileVersionMS      (offset +8)  high16 = major, low16 = minor
  //   DWORD dwFileVersionLS      (offset +12) high16 = build, low16 = revision
  const ms = buf.readUInt32LE(sigOffset + 8)
  const ls = buf.readUInt32LE(sigOffset + 12)
  return {
    major: (ms >>> 16) & 0xffff,
    minor: ms & 0xffff,
    build: (ls >>> 16) & 0xffff,
    revision: ls & 0xffff,
  }
}

/**
 * Write a small NSH header next to vc_redist.x64.exe that the NSIS installer
 * `!include`s to learn which redistributable version it bundles. Lets the
 * installer skip the multi-minute redist run when an equal-or-newer version
 * is already on the user's machine.
 */
function writeVcRedistVersionInclude(buildResourcesDir, vcRedistPath) {
  const v = readPeFileVersion(vcRedistPath)
  const versionStr = `${v.major}.${v.minor}.${v.build}.${v.revision}`
  const includePath = path.join(buildResourcesDir, 'vc_redist_version.nsh')
  const contents =
    `; Auto-generated by scripts/afterPack.mjs from vc_redist.x64.exe — do not edit.\n` +
    `!define VC_REDIST_VERSION "${versionStr}"\n`
  fs.writeFileSync(includePath, contents)
  console.log(`afterPack: wrote ${includePath} (VC_REDIST_VERSION=${versionStr})`)
}

async function ensureVcRedist(context) {
  const buildResourcesDir = context.packager.buildResourcesDir
  const vcRedistPath = path.join(buildResourcesDir, 'vc_redist.x64.exe')
  const vcRedistTempPath = `${vcRedistPath}.tmp`

  if (!fs.existsSync(vcRedistPath)) {
    console.log(`afterPack: downloading ${vcRedistUrl}`)
    const response = await fetch(vcRedistUrl)

    if (!response.ok || !response.body) {
      throw new Error(`Failed to download VC++ redistributable (${response.status} ${response.statusText})`)
    }

    fs.mkdirSync(buildResourcesDir, { recursive: true })
    await pipeline(Readable.fromWeb(response.body), fs.createWriteStream(vcRedistTempPath))
    fs.renameSync(vcRedistTempPath, vcRedistPath)
    console.log(`afterPack: saved ${vcRedistPath}`)
  }

  writeVcRedistVersionInclude(buildResourcesDir, vcRedistPath)
}

/**
 * electron-builder afterPack hook.
 * Ensures the 7zip-bin binary has the execute permission in the packaged output.
 * This is necessary because AppImage mounts are read-only, so runtime chmod fails.
 *
 * Switches on `context.electronPlatformName` (the *target* platform) rather
 * than `process.platform` (the *host*), so cross-builds — e.g. ToDesktop's
 * Mac/Linux build VMs producing Windows artifacts — pick the right branch.
 */
export default async function afterPack(context) {
  if (context.electronPlatformName === 'win32') {
    await ensureVcRedist(context)
    return
  }

  const unpackedDir = path.join(
    context.appOutDir,
    'resources',
    'app.asar.unpacked',
    'node_modules',
    '7zip-bin',
  )

  if (!fs.existsSync(unpackedDir)) return

  // Find all 7za binaries under the unpacked 7zip-bin directory
  for (const entry of fs.readdirSync(unpackedDir, { recursive: true })) {
    if (path.basename(String(entry)) === '7za') {
      const binPath = path.join(unpackedDir, String(entry))
      fs.chmodSync(binPath, 0o755)
      console.log(`afterPack: set +x on ${binPath}`)
    }
  }
}
